source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0.4'
gem 'uglifier', '~> 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'rom', '~> 0.9.1'
gem 'rom-rails', github: 'piasekhgw/rom-rails', branch: 'in-form-validation'
gem 'rom-sql', '~> 0.6.1'
gem 'rom-repository', '~> 0.1.0'
gem 'pry', '~> 0.10.1'
gem 'bcrypt-ruby', '~> 3.1.5', require: 'bcrypt'
gem 'simple_form', '~> 3.2.0'
gem 'haml-rails', '~> 0.9.0'
gem 'bootstrap-sass', '~> 3.3.5.1'
