source 'https://rubygems.org'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '~> 2.7.1'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'rom', '~> 0.9.1'
gem 'rom-rails', github: 'piasekhgw/rom-rails', branch: 'in-form-validation'
gem 'rom-sql', '~> 0.6.0'
gem 'pry', '~> 0.10.1'
gem 'omniauth-identity', '~> 1.1.1'
gem 'bcrypt', '~> 3.1.10'
